source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/prisma-ai/CocoaPodSpecs.git'

use_frameworks!

def internal_pods
  pod 'Alloy/Shaders'
  pod 'Smelter', :path => '../'
end

target 'Smelter Demo macOS' do
  platform :osx, '10.13'
  internal_pods
end

target 'Smelter Demo iOS' do
  platform :ios, '11.0'
  internal_pods
end
